### ISSUE TITLE
cfortran.h is non-free

### ISSUE THREAD

**Issue by opoplawski** [Unidata/netcdf-fortran#27]
See https://bugzilla.redhat.com/show_bug.cgi?id=1197893

FYI - This means we will need to be pulling the netcdf-fortran interface from the Fedora/EPEL packages.

**Comment by WardF** [comment]
Thanks for pointing this out; cfortran.h predates my involvement, and I'll discuss this with Russ.  I do want to clarify that the license document, `cfortran.doc`, *is* included in the netcdf-fortran distribution, albeit in an unusual location.  It can be found under `libsrc/cfortran.doc`.

Thanks again for pointing this out!

**Comment by WardF** [comment]
Upon further investigation, it appears that the cfortran.h license has been updated due to this issue causing problems with various linux distributions. The following updated license terms may be found at the bottom of http://cfortran.sourceforge.net/ (emphasis mine), and suggest that `cfortran.h` is "free" software after all, although I'm not sure what 'free' mean specifically to Fedora.

> THIS PACKAGE, I.E. CFORTRAN.H, THIS DOCUMENT, AND THE CFORTRAN.H EXAMPLE
PROGRAMS ARE PROPERTY OF THE AUTHOR WHO RESERVES ALL RIGHTS. THIS PACKAGE AND
**THE CODE IT PRODUCES MAY BE FREELY DISTRIBUTED WITHOUT FEES, SUBJECT 
(AT YOUR CHOICE) EITHER TO THE GNU LIBRARY GENERAL PUBLIC LICENSE OR TO THE
FOLLOWING RESTRICTIONS:**
- YOU MUST ACCOMPANY ANY COPIES OR DISTRIBUTION WITH THIS (UNALTERED) NOTICE.
- YOU MAY NOT RECEIVE MONEY FOR THE DISTRIBUTION OR FOR ITS MEDIA 
  (E.G. TAPE, DISK, COMPUTER, PAPER.)
- YOU MAY NOT PREVENT OTHERS FROM COPYING IT FREELY.
- YOU MAY NOT DISTRIBUTE MODIFIED VERSIONS WITHOUT CLEARLY DOCUMENTING YOUR
  CHANGES AND NOTIFYING THE AUTHOR.
- YOU MAY NOT MISREPRESENTED THE ORIGIN OF THIS SOFTWARE, EITHER BY EXPLICIT
  CLAIM OR BY OMISSION. 

I need to untangle which version this applies to for sure, and confirm that this is the latest project page for `cfortran`, but the "download" link takes us to a file apparently date-stamped `20110621`, which post-dates the version `4.3` released in July '98.  I notice the header for our version claims we are using cfortran.h `4.4`, but our included `cfortran.doc` is version 4.3.  It may just be that we need to update our included `cfortran.doc` to reflect the GPL licensing.

Of course this is all based on a quick back-of-the-envelope search; I'll look at this more closely this evening or tomorrow and follow up once I'm sure what the current license says.

**Comment by WardF** [comment]
Ok, it appears that `cfortran.h` is available under the LGPL from the original author.  

* Author's statement releasing `cfortran.h` under the GNU Library General Public License:  https://launchpad.net/ubuntu/precise/+source/cfortran/+copyright

> Date: Tue, 22 Oct 2002 12:48:00 -0400
>From: Burkhard D Steinmacher-burow <steinmac@us.ibm.com>
> To: Kevin B. McCarty <kmccarty@Princeton.EDU>
> Subject: Re: CFortran licensing question
> 
> Kevin,
>
> [Just noticed that I didn't send this yesterady.]
>
> I have no time right now to read through licenses.
> IIRC, library GPL is fairly unrestrictive, so I'll choose that. So.....
> 
> You may consider this e-mail as a notice that as an alternative to any
> other cfortran licenses,
> I hereby relase all versions and all parts of cfortran under the
> the Library GPL license.
> From among these licenses, the user is free to choose
> the license or licenses under which cfortran is used.
>
> Contact me if you'd like to be able to choose another license.
> 
> Burkhar

The terms of the GNU Library General Public license (https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html) entry 6 state that:

> As an exception to the Sections above, you may also compile or link a "work that uses the Library" with the Library to produce a work containing portions of the Library, and distribute that work under terms of your choice, provided that the terms permit modification of the work for the customer's own use and reverse engineering for debugging such modifications.

This still warrants a thorough read-through that I can't do right now, but it seems to me that `cfortran.h` is in-fact free software with a license compatible with inclusion in Fedora, although we will need to update our copy of `cfortran.doc` to make it clear that this is the case.  I'm not the expert in Fedora, however;  are there any roadblocks to inclusion remaining?

**Comment by russrew** [comment]
The whole issue may be moot anyway with netCDF Fortran 4.4.x releases since
Feb 2013, in which Richard Weed integrated support for use with Fortan
compilers that support Fortran 2003 C Interoperability interfaces. In that
case, I think there's no need for cfortran.h and it may not even be used in
the build (I'll have to check that). At this point almost all Fortran
compilers support that part of the Fortran 2003 standard.

**Comment by opoplawski** [comment]
yes, it does appear that it has been re-licensed under the LGPL, which is good news.  We'll just need to update the copyright/license info.

**Comment by russrew** [comment]
I verified that with a compiler that supports the Fortran-2003 C interoperability feature (such as gfortran), both configure and make check succeed, even if cfortran.h is deleted first.

**Comment by WardF** [comment]
I've updated the `cfortran.doc` license file to reflect the most recent version, which contains the LGPL licensing stanza.  This change was made in commit 2665fdc75ac7b3a54e3b2ea9de705daa5f1b955d.  I moved the license file into the `docs/` directory in commit b992ffa642ac67508e717822243a4230c678a451.

I'm closing this out since the issue seems resolved.  If there's still a question or any changes needed I can reopen it. Thanks!
