### ISSUE TITLE
Use fortran preprocessor

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-fortran#355]
It looks like most fortran compilers are capable of applying the C pre-processor
to the code before compiling.
Would it help clean up our fortran code if we began using a pre-processor?

**Comment by edwardhartnett** [comment]
Yes it would and we should.

All Fortran compiles out there will use the preprocessor on files that end in F90 (but not files that end in f90).

The NOAA Fortran code uses the preprocessor, and is still very widely portable and built on many machines.

**Comment by edwardhartnett** [comment]
I am going to suggest that after the next netcdf-fortran release, we switch to using pre-processor, starting with making all fortran file extensions F90 or F (i.e. no more f90 or f).

We have done this on many NOAA fortran libraries without a problem. We have not encountered any Fortran compilers which do not properly apply the pre-processor. However, if there are any such compilers, the pre-processor can still be run as a separate step by the user.

This will ensure the pre-processor is run everywhere.

But it will also royally hose-up any open PRs, because git doesn't seem to follow that a file has been renmaed. So this step is best done after the release, when open PRs are at a minimum.

@WardF what do you think of this plan?

**Comment by edwardhartnett** [comment]
OK, there is a fly in the ointment here. We cannot use the preprocessor as the code is currently structures. Here's some test code that illustrates the problem:

test1.F90:

```
#ifdef NOT_DEFINED
  print *,'pre-processing is not working'
#endif

```
test.F90:

```
program test
  print *,'howdy'
  include "test1.F90"
end program test

```

When compiled this gives the following compile warnings and the pre-processor directives are not working:

```
gfortran -Wall -o test test.F90
test1.F90:1:2:

    1 | #ifdef NOT_DEFINED
      |  1
Warning: Illegal preprocessor directive
test1.F90:3:2:

    3 | #endif
      |  1
Warning: Illegal preprocessor directive

ed@koko:~$ ./test
 howdy
 pre-processing is not working

```

So the pre-processor does not work in files included with the F90 include statement. But it does work if I change to the pre-processor #include.

Well maybe I should just do that in the netcdf-fortran code. I will test...
