### ISSUE TITLE
Can't open module file 'netcdf.mod' for reading at (1): No such file or directory

### ISSUE THREAD

**Issue by devineniraghava** [Unidata/netcdf-fortran#358]
Dear Unidata community, 

I am trying to install a software called PALM [https://palm.muk.uni-hannover.de/trac/wiki/doc/install](url) which works with NetCDF data. When installing this software i get the following error:

######################################################################
USE netcdf,                                                                   &
     1
Fatal Error: Can't open module file 'netcdf.mod' for reading at (1): No such file or directory
######################################################################

I tried to contact the PALM team also regarding this error. I am new to working with NetCDF or PALM. But if you have any idea where the problem could be please help me. 

I also attach the full log file for PALM installation 
[palm_installation_log_2.txt](https://github.com/Unidata/netcdf-fortran/files/8610971/palm_installation_log_2.txt)

Kind regards,
Krishna

**Comment by edwardhartnett** [comment]
Do you have netcdf-fortran installed? If so, do you know where? And is that location being communicated to the PALM build system?

I don't believe this is a netcdf-fortran issue...

**Comment by levi9874** [comment]
Have you already sovled the problem? I wish to know how to solve it. I face the same problem now and I'm so confused because I'm also new to working with NetCDF. Thank you so much

**Comment by WardF** [comment]
I'll second @edwardhartnett 's comment, this appears to be an issue with the netcdf-fortran install.  @levi9874 are you working with PALM as well? If so, can you provide additional information and I will re-open this issue.  Otherwise, if you want to open a new issue and provide more detailed information, we will try to get this sorted out.

**Comment by levi9874** [comment]
Thank you sooooooo much!!!!!!!! I just notice your helpful assistance. After faced the question, I found the reason is PALM can't know the files in my netCDF-fortran, just like your suggestion. Now I have installed the PALM model. I'm just a student in major of environmental engineering and want to know the effect of the PALM model simulation. No one taught me how to use it. I have to teach myself PALM. You must be an expert in PALM's field, and I hope to learn more from you.
