### ISSUE TITLE
ncf-fortran installation instructions

### ISSUE THREAD

**Issue by VictorEijkhout** [Unidata/netcdf-fortran#425]
1. Page https://docs.unidata.ucar.edu/netcdf-c/current/building_netcdf_fortran.html only has configure instructions, not the cmake configuration.
2. the link to the "fortran bootstrap procudure" https://docs.unidata.ucar.edu/netcdf-c/current/getting_and_building_netcdf.html#getting is broken.

**Comment by jstrodtb** [comment]
At this point, I am giving up, as I simply cannot figure out how to get the CMake build to work, and the provided configure.ac generates a broken configure script that looks for a nonexistent install.sh.

**Comment by WardF** [comment]
@jstrodtb which release are you using? I am not seeing this behavior on a released version, although I'll make sure it's fixed in the development branch.  @VictorEijkhout thanks for letting us know; the fortran bootstrap has been removed, and it will be removed from the documentation.  We are moving to `fetchcontent` functionality provided by cmake.
