### ISSUE TITLE
4.4.4 Release?

### ISSUE THREAD

**Issue by dlg0** [Unidata/netcdf-fortran#50]
Hi, just enquiring as to when there may be an official 4.4.4 release? I'm trying to get this build at NERSC to support a code that requires a bug fix in the present master. However, the NERSC staff are hesitant to build prior to an actual release.

Thanks for all your work on this.

**Comment by WardF** [comment]
@dlg0 We hope to have one out pretty soon; the release of HDF5 1.10.0 required a change of focus, but once the next netCDF-C release candidate is out (this week if all goes well) I'm going to try to roll out netCDF-Fortran 4.4.4 as well as the next C++ interface release.

**Comment by dlg0** [comment]
@WardF Thanks for the update.

**Comment by dlg0** [comment]
@WardF I'm trying to build (and have perhaps convinced the NERSC staff to build) a version of netcdf-fortran and netcdf-c that is not an official release. We are working with the test case presented in Unidata/netcdf-c#183 (since that's the bug that is causing our issues) but are unsure which branch of netcdf-fortran we should be building to reproduce the working capability you mention there. We're assuming that any variant of netcdf-c beyond 4.3.3.1 should be good (since you explicitly mention that in Unidata/netcdf-c#183), but are unclear on which netcdf-fortran branch to use (thus far using the master branch we've been unsuccessful in fixing the stride error). Any help here would be appreciated.

Thanks.

**Comment by WardF** [comment]
@dlg0 Since the fortran library is just an interface layer to the C library, I'm surprised to hear you are having problems with netcdf-fortran when linking against netcdf-c 4.4.0+.  I'm prepping the netcdf-fortran release for next week, but I'd like to see more about this stride error.  Can you provide additional information, perhaps the `config.log` version from the netcdf-fortran build?  Also, if you were able to supply example code demonstrating the stride error in netcdf-fortran, that would be very much appreciated.  If this bug is present in netcdf-fortran, I would sure like to have it fixed for the next release.

**Comment by WardF** [comment]
If we can confirm that the stride bug persists in netcdf-fortran, we should/will open a new issue to track it.

**Comment by dlg0** [comment]
Hmm, the test code presented in Unidata/netcdf-c#183 is fortran. 

So given that netcdf-fortran is a wrapper of the netcdf-c routines, @WardF, you are suggesting that any variant of netcdf-fortran built against netcdf-c/4.4.0 onwards should work. However, I _think_ that the test case does still fail when using the 4.4.0 build at NERSC.

@valiantljk Can you confirm that the test case in question fails when using the cray-netcdf/4.4.0 build?

I'm working on building both netcdf-c and netcdf-fortran to provide the `config.log` you requested.

**Comment by valiantljk** [comment]
@dlg0 @WardF ,
Yes, the test case fails using the cray-netcdf/4.4.0
Here is the output of the test case, @dlg0 you may want to share the code with @WardF. It's possible our nersc build has some issues. I appreciate. 

 ---> Creating netcdf file: foo.nc
 *****************************************************
 ---> Opening netcdf file: foo.nc
Array should be 1:nx, with nx = 12
   1.000000       2.000000       3.000000       4.000000       5.000000    
   6.000000       7.000000       8.000000       9.000000       10.00000    
   11.00000       12.00000    
 *****************************************************
 ---> Opening netcdf file: foo.nc
Using stride = 1
NCVPTG: : NetCDF: Illegal stride

**Comment by WardF** [comment]
> netCDF-C 4.4.0 and netCDF-Fortran, from the `master` branch, using `gfortran` on Ubuntu linux.

When I compile and run the test `ncvptg_test.f`, as-is from Unidata/netcdf-c#183, I am not getting an error:

````
 ---> Creating netcdf file: foo.nc
 *****************************************************
 ---> Opening netcdf file: foo.nc
Array should be 1:nx, with nx = 12
   1.00000000       2.00000000       3.00000000       4.00000000       5.00000000       6.00000000       7.00000000       8.00000000       9.00000000       10.0000000       11.0000000       12.0000000    
 *****************************************************
 ---> Opening netcdf file: foo.nc
Using stride = 1
 *****************************************************
 ---> Opening netcdf file: foo.nc
 Array elements 1:nx:stride should have sign flipped
nx = 12, stride = 1
  -1.00000000      -2.00000000      -3.00000000      -4.00000000      -5.00000000      -6.00000000      -7.00000000      -8.00000000      -9.00000000      -10.0000000      -11.0000000      -12.0000000    
 *****************************************************
````

I don't have access to a Cray system, but the issue (as I recall) really shouldn't have been platform dependent.  A few things will help track this down:

* Can you provide code that exhibits the issue, if you are not using the `ncvptg_test.f` referenced above?
* Can you confirm that the issue happens on a non-Cray system? 


I'm currently cleaning up the F90 interface documentation (having converted it to Doxygen/Markdown from .texi via Pandoc); once that's done I'm going to wire in this ncvptg test as part of the standard test suite and then will try to get the 4.4.4 release out the door.  If we can demonstrate this issue in a way that I can duplicate/debug it, I will make sure that the fix for it is also in the 4.4.4 release.

**Comment by valiantljk** [comment]
Hi, Thanks Ward, @WardF, 
I think I'm using the same code. 
Sure, but I may want to rebuild the library first. 
FYI, I have filed a bug report to Cray.

**Comment by WardF** [comment]
Will reopen if need be, but unless there is new information there's not much I can do to move forward with this at this time.
